-- =============================================================================
-- Section 11.5: Other Features
-- =============================================================================

-- =============================================================================
-- TODO [P2]: gen_random_uuid() — built-in UUID generation (PG 13+)
-- =============================================================================

SELECT gen_random_uuid() AS uuid1, gen_random_uuid() AS uuid2;

CREATE TABLE other_uuid_test (
    id   UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT
);
INSERT INTO other_uuid_test (name) VALUES ('test1'), ('test2');
SELECT * FROM other_uuid_test;
DROP TABLE other_uuid_test;

-- =============================================================================
-- TODO [P2]: GENERATED ALWAYS AS IDENTITY — standard identity column
-- =============================================================================

CREATE TABLE other_identity_test (
    id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT
);
INSERT INTO other_identity_test (name) VALUES ('Alice'), ('Bob');
SELECT * FROM other_identity_test;

-- GENERATED BY DEFAULT allows explicit values
CREATE TABLE other_identity_default (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);
INSERT INTO other_identity_default (name) VALUES ('Carol');
INSERT INTO other_identity_default (id, name) VALUES (100, 'Dave');
SELECT * FROM other_identity_default;

DROP TABLE other_identity_default;
DROP TABLE other_identity_test;

-- =============================================================================
-- TODO [P4]: Table inheritance (INHERITS) — see 49_table_inheritance.sql
-- =============================================================================

-- =============================================================================
-- TODO [P4]: TABLESAMPLE — see 61_tablesample.sql
-- =============================================================================

-- =============================================================================
-- TODO [P4]: Foreign Data Wrappers (FDW)
-- =============================================================================

-- CREATE EXTENSION IF NOT EXISTS postgres_fdw;
-- CREATE SERVER remote_server FOREIGN DATA WRAPPER postgres_fdw
--     OPTIONS (host 'localhost', dbname 'remote_db', port '5432');
-- CREATE USER MAPPING FOR CURRENT_USER SERVER remote_server
--     OPTIONS (user 'remote_user', password 'remote_pass');
-- CREATE FOREIGN TABLE remote_table (
--     id   INT,
--     name TEXT
-- ) SERVER remote_server OPTIONS (table_name 'actual_table');
-- SELECT * FROM remote_table;
-- DROP FOREIGN TABLE remote_table;
-- DROP USER MAPPING FOR CURRENT_USER SERVER remote_server;
-- DROP SERVER remote_server;
-- DROP EXTENSION IF EXISTS postgres_fdw;

-- =============================================================================
-- TODO [P4]: Logical replication — test DDL (pub/sub)
-- =============================================================================

-- CREATE PUBLICATION my_pub FOR ALL TABLES;
-- -- On subscriber:
-- -- CREATE SUBSCRIPTION my_sub CONNECTION '...' PUBLICATION my_pub;
-- DROP PUBLICATION IF EXISTS my_pub;

-- =============================================================================
-- TODO [P4]: Physical replication — test pg_is_in_recovery()
-- =============================================================================

-- SELECT pg_is_in_recovery() AS is_replica;
